### ISSUE TITLE
Selection Doesnt get updated in newest VSCode 

### ISSUE THREAD

**Issue by RaptorX** [kuone314/VSCodeExtensionInsertSequence#1]
When you start your sequence and update the formatting string, the selection gets lost and new strings get **appended** to the old ones.

![Insert Sequence Issue](https://user-images.githubusercontent.com/328761/229322921-1c912bab-31c9-42ba-acd6-ce31e82de1a6.gif)

I think there was a change in vs code that causes that.

**Comment by kuone314** [comment]
調査メモ: 選択が無い状態で `builder.replace` を読んだ後、置換後の文字列が選択状態にならなくなた事が原因。
